<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyTitle>Niflib.NET</AssemblyTitle>
    <Company>Dawn of Light</Company>
    <Product>Niflib.NET</Product>
    <Description>Niflib for .NET by NoOne</Description>
    <Copyright>GNU GPL v2</Copyright>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
